---
# - hosts: "app_north_virginia_lex_dev"
- hosts: "{{ deploy_host_name }}"
  become: yes
  strategy: free
  vars_files:
    - "vars/main.yml"
  roles:
    - role: deploy-credential-ms
      tags: [deploy-credential-ms]
    - role: deploy-cred-schema-ms
      tags: [deploy-cred-schema-ms]
    - role: deploy-did-l3
      tags: [deploy-did-l3]
    - role: stack-proxy
      tags: [stack-proxy]