---
# vars file for deploy-sb-ext
# For script
template_compose_file_name: compose-file.j2
template_env_file_name: env.j2
compose_file_name: "{{ service_middleware_service }}.yml"
env_file_name: "{{ service_middleware_service }}.env"
compose_file_deployment_location: "{{ compose_files_dir }}/{{ compose_file_name }}"
env_file_deployment_location: "{{ env_files_dir }}/{{ env_file_name }}"
user_friendly_name: middleware

docker_port: "{{ service_middleware_docker_port }}"
host_port: "{{ service_middleware_host_port }}"
image_name: "{{ image_middleware_service }}"
tag: "{{ tags_middleware_service }}"
replicas: "{{ service_replicas_middleware_service }}"
network_alias_name: "{{ network_alias_middleware_service }}"
docker_service_stack_name: ulp
docker_service_name: "{{ service_middleware_service }}"
force_reload: "{{ force_reload_middleware_service }}"
host_logs_location: "{{ middleware_logs }}"
docker_logs_location: /logs

# Your credentials on the vault
credentials: "{{ lookup('hashi_vault', 'secret={{ middleware_secret_path }}', url=VAULT_ADDR, token=VAULT_TOKEN) }}"
